services:

  hexi-php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app

  hexi-nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - hexi-php
